### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by karibdis** [Mchl/medal-bar-generator#12]
Hi, the maker does not works in any actual browser. It was the only one application of their type. I dont know anything about coding, could you make your last effort fixing the app?. thanks a lot.

**Comment by Mchl** [comment]
Should be fixed now. 
Alea.js was removed from CDN for whatever reason. Self-hosting it now.

**Comment by Mchl** [comment]
I am sorry I didn't fix it sooner. I missed a notification about this issue. :/
